### PR TITLE
Bring npm 7 compatibility and do some general package.json and webpack.config cleanups

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by KKoukiou** [comment]
@justin-stephenson hi :) Can you please help me understand this failure https://cockpit-session-recording.semaphoreci.com/jobs/a9011c0b-dfe5-4abc-908c-bf4a09e8ebd6 ? 
Locally make rpm works fine.

**Comment by justin-stephenson** [comment]
Thank you very much for the PR @KKoukiou ! Our CI was quite outdated, I merged this upstream https://github.com/Scribery/cockpit-session-recording/commit/e49176b966bdf194d673f602a4c478eacbafcb8a

Could you rebase this PR on top and we'll see if the CI runs as expected.

**Comment by justin-stephenson** [comment]
Test failure is unrelated, I'll do more localized testing and then this should be good to go. Thank you again.

**Comment by justin-stephenson** [comment]
> Test failure is unrelated, I'll do more localized testing and then this should be good to go. Thank you again.

@KKoukiou `make check` is failing locally on my laptop (fedora 34), do you know why that might be off hand? Full log http://pastebin.test.redhat.com/1008595
~~~
[justin@agalloch cockpit-session-recording]$ TEST_OS=fedora-35 make check
...
<snip>
...
git clone -b 256 --depth=1 https://github.com/cockpit-project/cockpit.git tmp/cockpit
Cloning into 'tmp/cockpit'...
remote: Enumerating objects: 1409, done.
remote: Counting objects: 100% (1409/1409), done.
remote: Compressing objects: 100% (1286/1286), done.
remote: Total 1409 (delta 245), reused 651 (delta 33), pack-reused 0
Receiving objects: 100% (1409/1409), 6.91 MiB | 15.22 MiB/s, done.
Resolving deltas: 100% (245/245), done.
Note: switching to '5335235f8f4c44e73c96d466df2e9bb35c95212b'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

mv tmp/cockpit/pkg/lib src/
rm -rf tmp/cockpit
NODE_ENV= npm run build

> session-recording@0.1.0 build /home/justin/github/cockpit-session-recording/rpmbuild/cockpit-session-recording
> webpack

sh: line 1: webpack: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! session-recording@0.1.0 build: `webpack`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the session-recording@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/justin/.npm/_logs/2021-11-16T15_24_11_558Z-debug.log
make[1]: *** [Makefile:71: dist/index.html] Error 1
make[1]: Leaving directory '/home/justin/github/cockpit-session-recording/rpmbuild/cockpit-session-recording'
error: Bad exit status from /var/tmp/rpm-tmp.sWQMvN (%install)
~~~

**Comment by justin-stephenson** [comment]
Reverting 436c32e388e4eac649aaa94d4775de02cc4fcfa7 and b0491178f10fd23915314a7af980a332efab8a56 fixes the above error, but i'm not sure what exactly is causing the webpack not found error.

**Comment by KKoukiou** [comment]
Commit https://github.com/Scribery/cockpit-session-recording/commit/b0491178f10fd23915314a7af980a332efab8a56 should have nothing to do with your issue, the code it introduces even runs before the error happens, namely from the above log:

```
mv tmp/cockpit/pkg/lib src/
rm -rf tmp/cockpit
NODE_ENV= npm run build
```

I suggest you try to build from scratch, run `git clean -dfx` and the your make check command from above. 

If this still does not work, we should check the version of NPM you your using maybe, compared to mine.

**Comment by justin-stephenson** [comment]
on top of this PR I applied some changes that were in the starter-kit Makefile and not in our Makefile, this appears to have fixed the `webpack command not found` issue.
~~~
[justin@agalloch cockpit-session-recording]$ git diff
diff --git a/Makefile b/Makefile
index 9622366..9379ea8 100644
--- a/Makefile
+++ b/Makefile
@@ -11,7 +11,7 @@ VM_IMAGE=$(CURDIR)/test/images/$(TEST_OS)
 # stamp file to check if/when npm install ran
 NODE_MODULES_TEST=package-lock.json
 # one example file in dist/ from webpack to check if that already ran
-WEBPACK_TEST=dist/index.html
+WEBPACK_TEST=dist/manifest.json
 # one example file in src/lib to check if it was already checked out
 LIB_TEST=src/lib/cockpit-po-plugin.js
 
@@ -55,11 +55,6 @@ update-po: po/$(PACKAGE_NAME).pot
                msgmerge --output-file=po/$$lang.po po/$$lang.po $<; \
        done
 
-dist/po.%.js: po/%.po $(NODE_MODULES_TEST)
-       mkdir -p $(dir $@)
-       po/po2json -m po/po.empty.js -o $@.js.tmp $<
-       mv $@.js.tmp $@
-
 #
 # Build/Install/dist
 #
@@ -67,11 +62,11 @@ dist/po.%.js: po/%.po $(NODE_MODULES_TEST)
 %.spec: %.spec.in
        sed -e 's/%{VERSION}/$(VERSION)/g' $< > $@
 
-$(WEBPACK_TEST): $(LIB_TEST) $(NODE_MODULES_TEST) $(shell find src/ -type f) package.json webpack.config.js $(patsubst %,dist/po.%.js,$(LINGUAS))
-       NODE_ENV=$(NODE_ENV) npm run build
+$(WEBPACK_TEST): $(NODE_MODULES_TEST) $(LIB_TEST) $(shell find src/ -type f) package.json webpack.config.js
+       NODE_ENV=$(NODE_ENV) node_modules/.bin/webpack
 
 watch:
-       NODE_ENV=$(NODE_ENV) npm run watch
+       NODE_ENV=$(NODE_ENV) node_modules/.bin/webpack --watch
 
 clean:
        rm -rf dist/
@@ -94,16 +89,15 @@ dist: $(TARFILE)
 # we don't ship node_modules for license and compactness reasons; we ship a
 # pre-built dist/ (so it's not necessary) and ship packge-lock.json (so that
 # node_modules/ can be reconstructed if necessary)
-$(TARFILE): NODE_ENV=production
+$(TARFILE): export NODE_ENV=production
 $(TARFILE): $(WEBPACK_TEST) cockpit-$(PACKAGE_NAME).spec
        if type appstream-util >/dev/null 2>&1; then appstream-util validate-relax --nonet *.metainfo.xml; fi
        mv node_modules node_modules.release
        touch -r package.json $(NODE_MODULES_TEST)
        touch dist/*
        tar --xz -cf cockpit-$(PACKAGE_NAME)-$(VERSION).tar.xz --transform 's,^,cockpit-$(PACKAGE_NAME)/,' \
-               --exclude cockpit-$(PACKAGE_NAME).spec.in \
-               $$(git ls-files) package-lock.json cockpit-$(PACKAGE_NAME).spec dist/
-       mv node_modules.release node_modules
+               --exclude cockpit-$(PACKAGE_NAME).spec.in --exclude node_modules \
+               $$(git ls-files) src/lib package-lock.json cockpit-$(PACKAGE_NAME).spec dist/
~~~



However, once the tests are executed each test is failing with the following error, note that we are currently checking out cockpit test API 229 version
~~~
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'chrome-remote-interface'
Require stack:
- /home/justin/github/cockpit-session-recording/test/common/chromium-cdp-driver.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/justin/github/cockpit-session-recording/test/common/chromium-cdp-driver.js:31:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/justin/github/cockpit-session-recording/test/common/chromium-cdp-driver.js'
  ]
}
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/home/justin/github/cockpit-session-recording/test/check-application", line 379, in testFilterSince
    self._filter(
  File "/home/justin/github/cockpit-session-recording/test/check-application", line 333, in _filter
    b, _ = self._login()
  File "/home/justin/github/cockpit-session-recording/test/check-application", line 21, in _login
    self.login_and_go(loc)
  File "/home/justin/github/cockpit-session-recording/test/common/testlib.py", line 957, in login_and_go
    self.browser.login_and_go(path, user=user, host=host, superuser=superuser, urlroot=urlroot, tls=tls)
  File "/home/justin/github/cockpit-session-recording/test/common/testlib.py", line 570, in login_and_go
    self.open(href, tls=tls)
  File "/home/justin/github/cockpit-session-recording/test/common/testlib.py", line 126, in open
    self.cdp.invoke("Page.navigate", url=href)
  File "/home/justin/github/cockpit-session-recording/test/common/cdp.py", line 109, in invoke
    res = self.command(cmd)
  File "/home/justin/github/cockpit-session-recording/test/common/cdp.py", line 119, in command
    self.start()
  File "/home/justin/github/cockpit-session-recording/test/common/cdp.py", line 264, in start
    self.invoke("Page.addScriptToEvaluateOnNewDocument", source=src, no_trace=True)
  File "/home/justin/github/cockpit-session-recording/test/common/cdp.py", line 109, in invoke
    res = self.command(cmd)
  File "/home/justin/github/cockpit-session-recording/test/common/cdp.py", line 126, in command
    raise RuntimeError("CDP broken")
RuntimeError: CDP broken
Journal extracted to TestApplication-testFilterSince-fedora-34-127.0.0.2-2201-FAIL.log.gz
Traceback (most recent call last):
  File "/home/justin/github/cockpit-session-recording/test/check-application", line 379, in testFilterSince
    self._filter(
  File "/home/justin/github/cockpit-session-recording/test/check-application", line 333, in _filter
    b, _ = self._login()
  File "/home/justin/github/cockpit-session-recording/test/check-application", line 21, in _login
    self.login_and_go(loc)
  File "/home/justin/github/cockpit-session-recording/test/common/testlib.py", line 957, in login_and_go
    self.browser.login_and_go(path, user=user, host=host, superuser=superuser, urlroot=urlroot, tls=tls)
  File "/home/justin/github/cockpit-session-recording/test/common/testlib.py", line 570, in login_and_go
    self.open(href, tls=tls)
  File "/home/justin/github/cockpit-session-recording/test/common/testlib.py", line 126, in open
    self.cdp.invoke("Page.navigate", url=href)
  File "/home/justin/github/cockpit-session-recording/test/common/cdp.py", line 109, in invoke
    res = self.command(cmd)
  File "/home/justin/github/cockpit-session-recording/test/common/cdp.py", line 119, in command
    self.start()
  File "/home/justin/github/cockpit-session-recording/test/common/cdp.py", line 264, in start
    self.invoke("Page.addScriptToEvaluateOnNewDocument", source=src, no_trace=True)
  File "/home/justin/github/cockpit-session-recording/test/common/cdp.py", line 109, in invoke
    res = self.command(cmd)
  File "/home/justin/github/cockpit-session-recording/test/common/cdp.py", line 126, in command
    raise RuntimeError("CDP broken")
RuntimeError: CDP broken

# Result testFilterSince (__main__.TestApplication) failed
# 1 TEST FAILED [15s on agalloch]
~~~

**Pull request merged**
