### PR TITLE
package.json: Bump esbuild and esbuild-sass-plugin

### PR DESCRIPTION
**Pull request by justin-stephenson**
esbuild-sass-plugin 2.10 got released as compatible with 2.8, but it is not compatible any more with esbuild 0.17.18. Bump both.

(cherry picked from commit d3b9064d635eca0b7b2ff1edca58b1a4f37062e8)

### CODE REVIEW

**Comment by spoore1** [comment]
Maybe try adding the following rpms as deps?

libglvnd-glx
libglvnd-egl

I had to do that elsewhere to get the tests to work in RHEL.

**Comment by justin-stephenson** [comment]
> Maybe try adding the following rpms as deps?
> 
> libglvnd-glx libglvnd-egl
> 
> I had to do that elsewhere to get the tests to work in RHEL.

I tried this but no luck, the xterm accessibility tree DOM values are not populating as expected even though there is output written to the terminal object. I also tried adding 'xterm-addon-canvas' (from https://github.com/cockpit-project/cockpit/commit/65471fd9fcbc09343fa66246889bb2c48032cf8a) but still the same issue. I am still trying to figure out what's going wrong here.

**Comment by martinpitt** [comment]
Sorry for the delay -- I investigated that this morning, and I know what's up. Indeed adding xterm-addon-canvas is right, see https://github.com/cockpit-project/cockpit/commit/65471fd9fcbc09343fa66246889bb2c48032cf8a .

But you specify `"xterm": "^5.1.0"` which actually pulls in version 5.2, and that indeed regresses the a11y tree: https://github.com/xtermjs/xterm.js/issues/4571

So I suggest to pin down xterm to `"5.1.0"` (no `^`), to avoid the regression.

**Comment by martinpitt** [comment]
> which actually pulls in version 5.2

See the build log:

> bundled(npm(tslib)) = 2.6.0 bundled(npm(xterm)) = 5.2.1

**Pull request merged**
