### PR TITLE
cockpit: Stop importing cockpit's base1/patternfly.css

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by martinpitt** [comment]
centos-8 failed the `testSearch` test on `assert b.text(".listing-ct").count("contractor") == occ`

Please use `self.assertEqual()` and similar in tests, so that they fail in a more useful way. But since Fedora succeeded, that may be a flake?

**Comment by martinpitt** [comment]
Please see the [deprecation announcement](https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/thread/2Q6AAQXGI5IE5D7XMTJUIKP3NIS3CIBL/) for some details.

**Comment by martinpitt** [comment]
@justin-stephenson Hello! Do you have some time to have a look at this? If there are some general questions about the approach, we are happy to discuss/explain them in person, of course. 

FTR, we are planning to remove that API for RHEL 9 and Fedora ~ 34.

**Comment by justin-stephenson** [comment]
@martinpitt We have an intern @benwilliamgraham now working on the project, he is almost done with this work and will be submitting a separate PR. It should be completed in the coming weeks.

**Comment by KKoukiou** [comment]
> @martinpitt We have an intern @benwilliamgraham now working on the project, he is almost done with this work and will be submitting a separate PR. It should be completed in the coming weeks.

Seperate PR would be fine of course - but this commit is somehow standardized between all commit plugins, and ideally we should keep the structure as is (of course if needed some CSS fixes this should be included).
Having a common configuration between all cockpit plugins will make it much easier for us to drop in and help with maintenance jobs like this one.

So please when you create another PR instead of this one mark me as reviewer so that I can see if the main principles we follow in other cockpit plugins are followed regarding the usage of patternfly.

**Comment by justin-stephenson** [comment]
> > @martinpitt We have an intern @benwilliamgraham now working on the project, he is almost done with this work and will be submitting a separate PR. It should be completed in the coming weeks.
> 
> Seperate PR would be fine of course - but this commit is somehow standardized between all cockpit plugins, and ideally we should keep the structure as is (of course if needed some CSS fixes this should be included).
> Having a common configuration between all cockpit plugins will make it much easier for us to drop in and help with maintenance jobs like this one.
> 
> So please when you create another PR instead of this one mark me as reviewer so that I can see if the main principles we follow in other cockpit plugins are followed regarding the usage of patternfly.

Understood, Ben was using this PR as a starting point and has made changes only as needed to fix broken components in our layout. I will make sure to add you as a Reviewer when the PR is opened up. Thanks to your team for the help, and providing this PR.

**Comment by martinpitt** [comment]
@justin-stephenson : Oh, if that is causing layout regressions, then of course don't merge it yet. This was supposed to not effectively change the UI, but some version desync between cockpit-bridge.rpm (which ships base1/patternfly.css) and these static file copies certainly would. Getting rid of this randomness is the major point of dropping that API. Thanks for the heads-up!

**Comment by justin-stephenson** [comment]
@KKoukiou @martinpitt Would you mind reviewing the PatternFly changes in Ben's PR https://github.com/Scribery/cockpit-session-recording/pull/59 to ensure it aligns with other modules, and follows general best practices? 

Please note that we had not moved any components to PatternFly 3, I suspect we needed more changes than modules which had already been using PF3. Ben also made an effort in the PR to move as many components to PF4 as possible.

**Pull request closed without merging**
