### PR TITLE
Test: Move from CDP to BiDi

### PR DESCRIPTION
**Pull request by aborah-sudo**
Move from CDP to BiDi

### CODE REVIEW

**Comment by spoore1** [comment]
FYI, I manually ran the tests on RHEL9 and I'm seeing this error on a lot of tests:

```
testlib.Error: Error: Using ':contains' when window.Sizzle is not available.
```

**Comment by justin-stephenson** [comment]
> FYI, I manually ran the tests on RHEL9 and I'm seeing this error on a lot of tests:
> 
> ```
> testlib.Error: Error: Using ':contains' when window.Sizzle is not available.
> ```

We removed installing `sizzle` from `run-test.sh` in this PR.

Looks like we need to build it as a dependency

**Comment by justin-stephenson** [comment]
I added another commit to this PR, let's see the CI result.

**Comment by justin-stephenson** [comment]
> Still saw the same errors with the new commit. I think we might still need the sizzle install in run-test.sh because it's installing on the container that runs the tests. That doesn't seem to contain sizzle from what I gather from the errors earlier. When I add an "npm install sizzle" after the "make bots" in the run-test.sh, it works again:
> 
> ```
> # TESTS PASSED [512s on 33f34f59e1f5, 0 destructive tests, 16 nondestructive tests: ]
> ```
> 
> Not sure if there's another way to include it in packages so it's installed in a way that the container sees it or if we just have to add it back.

I added it back and CI is now green, let's go with that for now.

**Review by spoore1 — APPROVED** [review]
Looks like all the testing-farm tests passed and my manual test is working now so I'm approving this one.

**Pull request merged**
