### PR TITLE
Handle byte-array encoded journal data

### PR DESCRIPTION
**Pull request by justin-stephenson**
Journalctl json output formats field values as JSON strings with the
exception:

  Fields containing non-printable or non-UTF8 bytes are encoded as arrays
  containing the raw bytes individually formatted as unsigned numbers.

### CODE REVIEW

**Comment by spbnick** [comment]
Hi Justin! Do you know why this was happening? Tlog should generate valid JSON, which should be valid UTF-8, and shouldn't make journal resort to this encoding.

**Comment by justin-stephenson** [comment]
Hi Nikolai, I need to investigate further what characters systemd is identifying as non-UTF8 in the tlog JSON message, it was not clear on initial troubleshooting.

If I understand correctly now, this code change in cockpit-session-recording should not be needed contingent on addressing the root of the issue.

**Comment by justin-stephenson** [comment]
Tlog is generating valid UTF-8, but the journal entry MESSAGE field data is identified as **non-printable** in systemd code because unicode control characters are found in this field:

https://github.com/systemd/systemd/blob/master/src/basic/utf8.c#L142

This leads to the byte-array encoding from the journalctl output

https://github.com/systemd/systemd/blob/master/src/shared/logs-show.c#L749-L766

Normally you can use the `--all` journalctl argument to avoid this, but this does not appear to work in conjunction with `--output=json`

**Comment by justin-stephenson** [comment]
The journalctl issue with `--all` was fixed in https://github.com/systemd/systemd/commit/8980058a3715f2dc96f38373b9550ef4e5b83662 but I was testing on an older systemd version(F30)

**Pull request merged**
